### ISSUE TITLE
Chocolat clones template without removing previous template

### ISSUE THREAD

**Issue by madks13** [beuted/ng-chocolat#1]
I need to apply burning to images on demand. When i tried to locate the element containing the image i was surprised to see that each time i open Chocolat, it simply adds another set of elements to the parent node, instead of reusing the existing one, or even deleting the one it created before.

Is this normal behaviour? Because currently each time the user closes Chocolat, then reopens it, it adds elements to the page. The page being a single page web site, it becomes really heavy if left alone.

**Comment by beuted** [comment]
Thanks for the feedback I'll try to have a look this wend.

**Comment by beuted** [comment]
Annnnnd I forgot...
I don't manage to reproduce your bug, can you show me an example of this bug (a plunker would be awesome) ?
Have you tried upgrading to the latest version of chocolat-js ? (in the bower file of ng-chocolat)
